### ISSUE TITLE
Perspectives don't work on POSTed queries

### ISSUE THREAD

**Issue by niklas-may** [rexxars/picosanity#22]
Perspectives are not implemented for POST queries. This test should validate the error.

```js
// This test will fail
test('POSTed queries with perspective', () => {
  const client = new Client({
    ...config,
    token,
    apiVersion: 'v2021-03-25',
    useCdn: false,
    perspective: 'previewDrafts',
  })
  const ws = ' '.repeat(11 * 1024)

  return client.fetch(`*[_id == $id]${ws}[0]`, {id: expectedDoc._id}).then((res) =>
    expect(res).toMatchObject({
      ...expectedDoc,
      title: expectedDraft.title,
      _originalId: expectedDraft._id,
    }),
  )
})
```

If I read the [implementation](https://github.com/sanity-io/client/blob/ba2132a846ca40867b81809547ad783fe08a8d00/test/client.test.ts#L1418C14-L1418C14) on the sanity client correctly, POSTed queries send the perspective using a query param.

[PR](https://github.com/rexxars/picosanity/pull/23) available

**Comment by rexxars** [comment]
Fixed in #23 - thank you!
